#define init_data_file "init_data.txt"
#define MALE "Male"
#define FEMALE "Female"
#define BLANK """"
#define SUCCESS 0
#define FAILURE -1
#define input_data_file "database/input_data.dat"
#define ADD_CHILD "ADD_CHILD"
#define GET_RELATIONSHIP "GET_RELATIONSHIP"
#define INVALID_COMMAND "INVALID COMMAND!"
#define PATERNAL_UNCLE "Paternal-Uncle"
#define MATERNAL_UNCLE "Maternal-Uncle"
#define PATERNAL_AUNT "Paternal-Aunt"
#define MATERNAL_AUNT "Maternal-Aunt"
#define SISTER_IN_LAW "Sister-In-Law"
#define BROTHER_IN_LAW "Brother-In-Law"
#define SON "Son"
#define DAUGHTER "Daughter"
#define SIBLINGS "Siblings"
#define NOT_YET_IMPLEMENTED "NOT YET IMPLEMENTED"
#define PERSON_NOT_FOUND "PERSON_NOT_FOUND"
#define PROVIDE_VALID_RELATION "PROVIDE VALID RELATION"
#define CHILD_ADDITION_FAILED "CHILD_ADDITION_FAILED"
#define CHILD_ADDITION_SUCCEEDED "CHILD_ADDITION_SUCCEEDED"
#define NONE "NONE"
#define ADD_FAMILY_HEAD "ADD_FAMILY_HEAD"
#define ADD_SPOUSE "ADD_SPOUSE"
